#!/usr/bin/env bash
set -euo pipefail

fail() {
  echo "[ai-footprint-guard] $*" >&2
  exit 1
}

BASE_REF="${BASE_REF:-${GITHUB_BASE_REF:-}}"
BASE_SHA="${BASE_SHA:-${PR_BASE_SHA:-}}"
HEAD_SHA="${HEAD_SHA:-${PR_HEAD_SHA:-${GITHUB_SHA:-}}}"

if [[ "${GITHUB_ACTIONS:-}" == "true" && -n "${BASE_REF}" && "${TRUSTED_GUARD_EXECUTION:-0}" != "1" ]]; then
  git fetch --no-tags --depth=1 origin "${BASE_REF}" >/dev/null 2>&1 || fail "Unable to fetch base branch '${BASE_REF}'"

  trusted_script="$(mktemp)"
  trap 'rm -f "${trusted_script}"' EXIT

  git show "FETCH_HEAD:tools/ci/ai-footprint-guard.sh" > "${trusted_script}" 2>/dev/null || \
    fail "Trusted guard script not available on base branch; failing closed"

  [[ -s "${trusted_script}" ]] || fail "Trusted guard script is empty; failing closed"

  chmod +x "${trusted_script}"
  TRUSTED_GUARD_EXECUTION=1 BASE_REF="${BASE_REF}" BASE_SHA="${BASE_SHA}" HEAD_SHA="${HEAD_SHA}" "${trusted_script}" "$@"
  exit $?
fi

[[ -n "${BASE_SHA}" && -n "${HEAD_SHA}" ]] || fail "Missing BASE_SHA/HEAD_SHA range"

range="${BASE_SHA}...${HEAD_SHA}"
pattern='(chatgpt|gpt-?[0-9]|claude|copilot|openai|anthropic|cursor|gemini|llm|large language model|ai[- ]?generated|generated by ai|co-authored-by:.*(claude|copilot|chatgpt|openai))'

if git log --format=%B "${BASE_SHA}..${HEAD_SHA}" | grep -Eiq "${pattern}"; then
  fail "AI footprint detected in commit messages"
fi

if git diff --name-only "${range}" | grep -Eiq "${pattern}"; then
  fail "AI footprint detected in changed file names"
fi

if git diff --unified=0 --no-color "${range}" \
  -- . \
  ':(exclude)package-lock.json' \
  ':(exclude)pnpm-lock.yaml' \
  ':(exclude)yarn.lock' \
  ':(exclude)**/dist/**' \
  ':(exclude)**/build/**' \
  ':(exclude)**/vendor/**' \
  | awk '/^\+[^+]/ { print substr($0,2) }' \
  | grep -Eiq "${pattern}"; then
  fail "AI footprint detected in added lines"
fi

echo "[ai-footprint-guard] OK"
